services:
  DMP\CQRS\:
    resource: '../src/*'
    autowire: true
    autoconfigure: true

  DMP\CQRS\Infrastructure\Bus\Command\CommandBus:
    arguments:
      - '@messenger.bus.command'

  DMP\CQRS\Infrastructure\Bus\Event\EventBus:
    arguments:
      - '@messenger.bus.event'

  DMP\CQRS\Infrastructure\Bus\Query\QueryBus:
    arguments:
      - '@messenger.bus.query'
