services:
  DMP\CQRS\:
    resource: '../src/*'
    autowire: true
    autoconfigure: true

  DMP\CQRS\Infrastructure\Bus\Command\CommandDispatcher:
    arguments:
      - '@messenger.bus.command'

  DMP\CQRS\Infrastructure\Bus\Event\EventDispatcher:
    arguments:
      - '@messenger.bus.event'

  DMP\CQRS\Infrastructure\Bus\Query\QueryDispatcher:
    arguments:
      - '@messenger.bus.query'
